version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build:
    docker:
      - image: cimg/php:8.2-browsers

    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo apt-get install -y php-mbstring php-xml php-zip

      - run:
          name: "Create Environment File"
          command: mv .env.testing .env

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - vendor

      - run:
          name: "Generate App Key"
          command: php artisan key:generate

      - run:
          name: "Run Unit Tests"
          command: ./vendor/bin/phpunit tests/Unit

      - run:
          name: "Install sqlite"
          command: sudo apt-get install -y php-sqlite3

      - run:
          name: "Create Database and Run Migrations"
          command: |
            touch database/database.sqlite
            php artisan migrate --env=testing --force -vvv

      - run:
          name: "Dump Composer Autoload"
          command: composer dump-autoload

      - run:
          name: "Run Feature Tests"
          command: ./vendor/bin/phpunit tests/Feature

      - run:
          name: "Install Laravel Dusk and Dusk Updater"
          command: |
            composer require --dev laravel/dusk
            composer require --dev staudenmeir/dusk-updater
            php artisan dusk:update --detect

      - run:
          name: "Start Laravel Server"
          command: php artisan serve
          background: true

      - run:
          name: "Run Browser Tests"
          command: php artisan dusk
