version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8  # Updated orb version

jobs:
  build:
    docker:
      - image: cimg/php:8.2-browsers  # Updated PHP version to 8.2

    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: "Create Environment File"
          command: mv .env.testing .env

      - run:
          name: "Show .env File"
          command: |
            echo "Contents of .env file:"
            cat .env

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install --no-interaction --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - vendor

      - run:
          name: "Generate App Key"
          command: php artisan key:generate

      - run:
          name: "Set Directory Permissions"
          command: sudo chmod -R 0777 storage bootstrap/cache

      - run:
          name: "Install SQLite Extension"
          command: sudo apt-get update && sudo apt-get install -y php-sqlite3

      - run:
          name: "Create Database and Run Migrations"
          command: |
            touch database/database.sqlite
            php artisan migrate --env=testing --force

      - run:
          name: "Run Unit Tests"
          command: ./vendor/bin/phpunit tests/Unit

      - run:
          name: "Run Feature Tests"
          command: ./vendor/bin/phpunit tests/Feature

      - run:
          name: "Install Laravel Dusk and Dusk Updater"
          command: |
            composer require --dev laravel/dusk
            composer require --dev staudenmeir/dusk-updater

      - run:
          name: "Update ChromeDriver"
          command: php artisan dusk:update --detect

      - run:
          name: "Run Dusk Tests"
          command: php artisan dusk --debug -vvv

      - run:
          name: "Show Laravel Logs"
          when: always
          command: |
            if [ -f storage/logs/laravel.log ]; then
              echo "Contents of storage/logs/laravel.log:"
              cat storage/logs/laravel.log
            else
              echo "No Laravel logs found."
            fi
