version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build:
    docker:
      - image: cimg/php:8.2-browsers

    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip

      - run:
          name: "Create Environment file"
          command: |
            mv .env.testing .env

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Generate App key"
          command: php artisan key:generate

      - run:
          name: "Install Sqlite"
          command: |
            sudo apt-get update
            sudo apt-get install -y php-sqlite3
            touch database/database.sqlite
            php artisan migrate --env=testing

      - run:
          name: "Run Unit Tests"
          command: ./vendor/bin/phpunit tests/Unit

      - run:
          name: "Run Feature Tests"
          command: ./vendor/bin/phpunit tests/Feature

      - run:
          name: "Install Dusk and Update ChromeDriver"
          command: |
            composer require --dev laravel/dusk
            composer require --dev staudenmeir/dusk-updater
            php artisan dusk:chrome-driver --detect

      - run:
          name: "Run Laravel Server"  # Start the server and capture logs
          command: |
            php artisan serve --host=127.0.0.1 --port=8001 > server.log 2>&1 &
          background: true

      - run:
          name: "Wait for Laravel Server"  # Check port 8001 for server availability
          command: |
            timeout=60
            elapsed=0
            until curl --output /dev/null --silent --head --fail http://127.0.0.1:8001; do
              if [ "$elapsed" -ge "$timeout" ]; then
                echo "Timeout waiting for Laravel server to start."
                exit 1
              fi
              echo 'Waiting for Laravel server...'
              sleep 5
              elapsed=$((elapsed + 5))
            done

      - run:
          name: "Show Server Logs"  # Display server logs if the server fails to start
          command: cat server.log

      - run:
          name: "Run Browser Tests"
          command: php artisan dusk
